export const state = {
  messages: {},
  currentLang: document.documentElement.lang === "en" ? "en" : "zh-Hant",
  yamlErrorMarker: null,
  validateTimer: 0,
  checkBusy: false,
  lastYamlResult: null,
  lastStatus: { state: "", key: "status.idle" },
  files: [],
  versions: [],
  currentFile: null,
  previewVersion: null,
  dirty: false,
  loadingFile: false,
  saving: false,
  viewMode: localStorage.getItem("editorView") === "yaml" ? "yaml" : "nodes",
  flowCanvas: null,
  syncingYaml: false,
  editor: null,
};
